[profile.default]
src = "src"
out = "out"
libs = ["lib"]
test = "test"
script = "script"
eth-rpc-url = "https://testnet-rpc.monad.xyz"
chain_id = 10143
solc_version = "0.8.24"

[rpc_endpoints]
monad_testnet = "https://testnet-rpc.monad.xyz"
